#!/usr/bin/env bash
# oma-upgrade.sh — Upgrade-Safe OMA upgrade orchestrator
#
# WHY: OMA's compiled binary at `~/.bun/install/global/node_modules/oh-my-agent/bin/cli.js`
# gets overwritten by `oma update` and the `auto_update_cli: true` background check.
# Our local OMA source (`$OMA_SRC`) carries 55+ file modifications that implement:
#   - Windows codex.exe/.cmd auto-detection (Issue #1)
#   - Result-file fallback creation + antigravity stdout source (Issue #7, #8)
#   - `## Charter` + `CHARTER_CHECK` auto-line in result template
#   - `AGENT_TYPES` includes "docs" for `oma verify docs`
#   - `findResultFile` prioritizes `.agents/results` over `.serena/memories`
#   - Plus Codex's Windows wrapper fix + Antigravity headless dispatcher
#
# STRATEGY: git stash workflow
#   1. Backup global cli.js
#   2. `git stash --include-untracked` to fully preserve our working state
#   3. `git pull --rebase origin main` to fetch latest OMA upstream
#   4. `git stash pop` to reapply our changes (may surface merge conflicts)
#   5. On conflict: stop, surface to user, do NOT auto-resolve
#   6. On clean: typecheck → build → deploy → drift verify → spawn verify
#   7. Any failure rolls back to the pre-upgrade state
#
# USAGE:
#   bash scripts/oma-upgrade.sh              # full upgrade
#   bash scripts/oma-upgrade.sh --skip-spawn # skip the $0.1 spawn-verify step
#   bash scripts/oma-upgrade.sh --check-only # only run drift detection, no upgrade
#
# REQUIRES: bun, git, sha256sum, grep (all available in Git Bash on Windows)

set -euo pipefail

# ─────────────────────────────────────────────────────────────────────────────
# Config
# ─────────────────────────────────────────────────────────────────────────────
OMA_SRC="C:/Users/user/AI_Orchestra_Lab/core_system/oh-my-agent"
GLOBAL_CLI="C:/Users/user/.bun/install/global/node_modules/oh-my-agent/bin/cli.js"
PROJECT_ROOT="C:/Users/user/AI_Orchestra_Lab/projects"
BACKUP_DIR="$PROJECT_ROOT/backups/oma-upgrade-$(date +%Y%m%d-%H%M%S)"
MARKER_1="CHARTER_CHECK: auto-generated by OMA spawn-status"
MARKER_2="antigravity stdout"

SKIP_SPAWN=0
CHECK_ONLY=0
for arg in "$@"; do
  case "$arg" in
    --skip-spawn) SKIP_SPAWN=1 ;;
    --check-only) CHECK_ONLY=1 ;;
    -h|--help)
      sed -n '2,32p' "$0"
      exit 0 ;;
  esac
done

# ─────────────────────────────────────────────────────────────────────────────
# Helpers
# ─────────────────────────────────────────────────────────────────────────────
log()  { printf '\033[36m[oma-upgrade]\033[0m %s\n' "$*"; }
ok()   { printf '\033[32m[ok]\033[0m %s\n' "$*"; }
warn() { printf '\033[33m[warn]\033[0m %s\n' "$*"; }
err()  { printf '\033[31m[err]\033[0m %s\n' "$*" >&2; }

drift_check() {
  if [ ! -f "$GLOBAL_CLI" ]; then
    err "Global cli.js not found at $GLOBAL_CLI"
    return 2
  fi
  if grep -q "$MARKER_1" "$GLOBAL_CLI" && grep -q "$MARKER_2" "$GLOBAL_CLI"; then
    return 0
  fi
  return 1
}

# ─────────────────────────────────────────────────────────────────────────────
# Mode: --check-only (drift detection)
# ─────────────────────────────────────────────────────────────────────────────
if [ "$CHECK_ONLY" -eq 1 ]; then
  log "Running drift detection on global cli.js"
  if drift_check; then
    ok "Global cli.js carries our local patches (clean)"
    exit 0
  else
    err "DRIFT DETECTED — global cli.js is missing our markers."
    err "Run 'bash scripts/oma-upgrade.sh' (without --check-only) to restore."
    exit 1
  fi
fi

# ─────────────────────────────────────────────────────────────────────────────
# Pre-flight
# ─────────────────────────────────────────────────────────────────────────────
log "Pre-flight checks"

[ -d "$OMA_SRC/.git" ] || { err "OMA source git repo not found: $OMA_SRC"; exit 1; }
command -v bun  >/dev/null || { err "bun is required but not installed"; exit 1; }
command -v git  >/dev/null || { err "git is required but not installed"; exit 1; }
command -v sha256sum >/dev/null || { err "sha256sum is required (Git Bash)"; exit 1; }

cd "$OMA_SRC"
PRE_HEAD=$(git rev-parse HEAD)
PRE_BRANCH=$(git rev-parse --abbrev-ref HEAD)
ok "OMA source HEAD: $PRE_HEAD ($PRE_BRANCH)"

# Verify branch is main (or warn)
if [ "$PRE_BRANCH" != "main" ]; then
  warn "Current branch is '$PRE_BRANCH', expected 'main'. Proceeding anyway."
fi

# ─────────────────────────────────────────────────────────────────────────────
# Step 1 — Backup global cli.js
# ─────────────────────────────────────────────────────────────────────────────
log "Backing up global cli.js to $BACKUP_DIR"
mkdir -p "$BACKUP_DIR"
cp "$GLOBAL_CLI" "$BACKUP_DIR/cli.js.before-upgrade" || { err "Failed to backup global cli.js"; exit 1; }
PRE_GLOBAL_SHA=$(sha256sum "$GLOBAL_CLI" | awk '{print $1}')
echo "$PRE_GLOBAL_SHA  cli.js.before-upgrade" > "$BACKUP_DIR/SHA256.txt"
ok "Backup saved: $BACKUP_DIR/cli.js.before-upgrade ($PRE_GLOBAL_SHA)"

# ─────────────────────────────────────────────────────────────────────────────
# Step 2 — Stash local working state
# ─────────────────────────────────────────────────────────────────────────────
STASH_MSG="oma-upgrade-$(date +%s)-$$"
log "Stashing local working state with message: $STASH_MSG"
if ! git stash push --include-untracked --message "$STASH_MSG" 2>&1 | tee -a "$BACKUP_DIR/stash.log"; then
  warn "No local changes to stash (working dir already clean)."
fi
STASH_REF=$(git stash list | grep "$STASH_MSG" | head -1 | awk -F: '{print $1}' || echo "")
ok "Stash reference: ${STASH_REF:-none}"

# Rollback helper
rollback_stash() {
  log "Rolling back: restoring stashed working state"
  if [ -n "$STASH_REF" ]; then
    git stash pop "$STASH_REF" || warn "Stash pop failed; check 'git stash list' manually"
  fi
}

# ─────────────────────────────────────────────────────────────────────────────
# Step 3 — Fetch upstream
# ─────────────────────────────────────────────────────────────────────────────
log "Fetching origin/main"
git fetch origin main 2>&1 | tee -a "$BACKUP_DIR/fetch.log" || { err "git fetch failed"; rollback_stash; exit 1; }

REMOTE_HEAD=$(git rev-parse origin/main)
if [ "$PRE_HEAD" = "$REMOTE_HEAD" ]; then
  ok "Already up-to-date with origin/main ($REMOTE_HEAD). No pull needed."
else
  log "Updating: $PRE_HEAD → $REMOTE_HEAD"
  if ! git pull --rebase origin main 2>&1 | tee -a "$BACKUP_DIR/pull.log"; then
    err "git pull --rebase failed. Attempting rollback."
    git rebase --abort 2>/dev/null || true
    rollback_stash
    exit 1
  fi
  ok "Pull complete. New HEAD: $(git rev-parse HEAD)"
fi

# ─────────────────────────────────────────────────────────────────────────────
# Step 4 — Restore our local changes
# ─────────────────────────────────────────────────────────────────────────────
if [ -n "$STASH_REF" ]; then
  log "Restoring local changes via git stash pop"
  if ! git stash pop "$STASH_REF" 2>&1 | tee -a "$BACKUP_DIR/stash-pop.log"; then
    err "git stash pop produced conflicts. Working state is NOT clean."
    err "Stashed changes are preserved. Inspect with: git status"
    err "Resolve conflicts manually, then run: bash scripts/oma-upgrade.sh --resume"
    err "Or fully rollback with: git reset --hard $PRE_HEAD && git stash pop $STASH_REF"
    exit 1
  fi
  ok "Stash restored. Working dir matches our previous local state on top of new origin/main."
fi

# ─────────────────────────────────────────────────────────────────────────────
# Step 5 — Typecheck + Build
# ─────────────────────────────────────────────────────────────────────────────
log "Running bun run typecheck"
if ! bun run typecheck 2>&1 | tee -a "$BACKUP_DIR/typecheck.log"; then
  err "Typecheck failed. Working state preserved. Rollback manually:"
  err "  git reset --hard $PRE_HEAD"
  exit 1
fi
ok "Typecheck passed"

log "Running bun run build"
if ! bun run build 2>&1 | tee -a "$BACKUP_DIR/build.log"; then
  err "Build failed. Working state preserved. Rollback manually:"
  err "  git reset --hard $PRE_HEAD"
  exit 1
fi
ok "Build complete: cli/bin/cli.js"

LOCAL_CLI="$OMA_SRC/cli/bin/cli.js"
[ -f "$LOCAL_CLI" ] || { err "Build output missing: $LOCAL_CLI"; exit 1; }

# ─────────────────────────────────────────────────────────────────────────────
# Step 6 — Deploy to global
# ─────────────────────────────────────────────────────────────────────────────
log "Deploying to global: $GLOBAL_CLI"
cp "$LOCAL_CLI" "$GLOBAL_CLI" || { err "Failed to deploy"; cp "$BACKUP_DIR/cli.js.before-upgrade" "$GLOBAL_CLI"; exit 1; }
NEW_GLOBAL_SHA=$(sha256sum "$GLOBAL_CLI" | awk '{print $1}')
echo "$NEW_GLOBAL_SHA  cli.js.after-upgrade" >> "$BACKUP_DIR/SHA256.txt"
ok "Deployed: SHA256 $NEW_GLOBAL_SHA"

# ─────────────────────────────────────────────────────────────────────────────
# Step 7 — Drift verify
# ─────────────────────────────────────────────────────────────────────────────
log "Verifying patches are present in global cli.js"
if ! drift_check; then
  err "DRIFT VERIFY FAILED. Restoring previous global cli.js."
  cp "$BACKUP_DIR/cli.js.before-upgrade" "$GLOBAL_CLI"
  exit 1
fi
ok "Drift verify passed: both markers present"

# ─────────────────────────────────────────────────────────────────────────────
# Step 8 — Spawn verify (optional)
# ─────────────────────────────────────────────────────────────────────────────
if [ "$SKIP_SPAWN" -eq 0 ]; then
  log "Spawn verify: oma agent:spawn docs -m antigravity (~\$0.02)"
  cd "$PROJECT_ROOT"
  SESSION="upgrade-verify-$(date +%s)"
  WS="./oma-3vendor-live-test"
  mkdir -p "$WS"

  if ! oma agent:spawn docs "Reply exactly: oma-upgrade-verified" "$SESSION" -m antigravity -w "$WS" 2>&1 | tee -a "$BACKUP_DIR/spawn-verify.log"; then
    err "Spawn failed. Check $BACKUP_DIR/spawn-verify.log"
    err "Global cli.js is updated but verification incomplete."
    exit 1
  fi

  RESULT_FILE="$WS/.agents/results/result-docs-${SESSION}.md"
  if [ -f "$RESULT_FILE" ]; then
    if grep -q "oma-upgrade-verified" "$RESULT_FILE" && grep -q "Source: antigravity stdout" "$RESULT_FILE"; then
      ok "Spawn verify passed: result file + antigravity source confirmed"
    else
      warn "Result file exists but expected content missing. Inspect: $RESULT_FILE"
    fi
  else
    warn "Expected result file not found: $RESULT_FILE"
  fi
else
  warn "Skipping spawn verify (--skip-spawn). Drift check passed but live behavior not exercised."
fi

# ─────────────────────────────────────────────────────────────────────────────
# Done
# ─────────────────────────────────────────────────────────────────────────────
cat <<EOF

══════════════════════════════════════════════════════════════════════════════
✅ OMA upgrade complete

  Source HEAD : $(cd "$OMA_SRC" && git rev-parse HEAD) (branch: $PRE_BRANCH)
  Pre  cli.js : $PRE_GLOBAL_SHA
  Post cli.js : $NEW_GLOBAL_SHA
  Backup dir  : $BACKUP_DIR

  Markers present: ✓ "$MARKER_1"
                   ✓ "$MARKER_2"

Next:
  oma doctor                        # health check
  bash scripts/oma-check-drift.sh   # confirm patches still present anytime
══════════════════════════════════════════════════════════════════════════════
EOF
