#!/usr/bin/env bash
# oma-check-drift.sh — Standalone drift detection for OMA global cli.js
#
# Checks whether the currently-installed global OMA binary carries our local
# patches (Codex Windows fix, Antigravity headless dispatcher, charter block,
# docs AGENT_TYPE, verify findResultFile priority).
#
# Exit codes:
#   0 — clean (markers present)
#   1 — drift detected (markers missing — run `oma-upgrade.sh` to restore)
#   2 — error (cli.js not found / unreadable)
#
# Usage:
#   bash scripts/oma-check-drift.sh
#   bash scripts/oma-check-drift.sh --quiet   # suppress output, return exit code only

set -eu

GLOBAL_CLI="C:/Users/user/.bun/install/global/node_modules/oh-my-agent/bin/cli.js"
MARKER_1="CHARTER_CHECK: auto-generated by OMA spawn-status"
MARKER_2="antigravity stdout"

QUIET=0
[ "${1:-}" = "--quiet" ] && QUIET=1

log() {
  [ "$QUIET" -eq 0 ] && printf '%s\n' "$*"
}

if [ ! -f "$GLOBAL_CLI" ]; then
  log "[err] Global cli.js not found: $GLOBAL_CLI"
  exit 2
fi

MARKER_1_OK=0
MARKER_2_OK=0
grep -q "$MARKER_1" "$GLOBAL_CLI" && MARKER_1_OK=1
grep -q "$MARKER_2" "$GLOBAL_CLI" && MARKER_2_OK=1

if [ "$MARKER_1_OK" -eq 1 ] && [ "$MARKER_2_OK" -eq 1 ]; then
  log "✓ Global cli.js carries our local patches (clean)"
  log "  ✓ marker 1: $MARKER_1"
  log "  ✓ marker 2: $MARKER_2"
  exit 0
fi

# Drift detected
log "⚠️  DRIFT DETECTED — global cli.js is missing local patches."
log ""
log "  marker 1 ($MARKER_1): $( [ "$MARKER_1_OK" -eq 1 ] && echo present || echo MISSING )"
log "  marker 2 ($MARKER_2): $( [ "$MARKER_2_OK" -eq 1 ] && echo present || echo MISSING )"
log ""
log "  영향: oma agent:spawn -m antigravity 동작 안 됨, codex Windows spawn 실패 가능."
log "  복구: bash scripts/oma-upgrade.sh"
log ""
exit 1
